version: "3.1"

volumes:
  dbdata:

networks:
  <application_name>:

services:

  db:
    image: mysql:8.0
    container_name: <project_name>-db
    ports:
      - "3308:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: <project_name>
      MYSQL_USER: <project_name>
      MYSQL_PASSWORD: <project_name>
    networks:
      - <application_name>

  php-fpm:
    build: phpdocker/php-fpm
    container_name: <project_name>-php-fpm
    volumes:
      - ./:/var/www/<application_name>/
    user: 1000:1000
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      APPLICATION_CONTAINER_NAME: <application_name>
    networks:
      - <application_name>
    depends_on:
      - db
    links:
      - db

  webserver:
    image: nginx
    container_name: <project-name>-webserver
    ports:
      - "80:80"
    volumes:
      - .:/var/www/<application_name>/
      - ./phpdocker/nginx:/etc/nginx/templates
    environment:
      NGINX_PORT: 80
      NGINX_HOST: "<project-name>.local"
      DOCKER_PHP: php-fpm
      APPLICATION_NAME: <application_name>
    depends_on:
      - php-fpm
    links:
      - php-fpm
    networks:
      <application_name>:
        aliases:
          - ssymfony.local

  mailhog:
    image: mailhog/mailhog:latest
    container_name: <project-name>-mailhog
    ports:
      - "8025:8025"

#  redis:
#    image: redis:alpine
#    container_name: <project-name>-redis
#
#  elasticsearch:
#    image: elasticsearch:6.5.4
#    container_name: <project-name>-elasticsearch
